<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Neo.Builders</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Neo/Neo.csproj" />
    <ProjectReference Include="../Neo.Core/Neo.Core.csproj" />
    <ProjectReference Include="../Neo.Cryptography/Neo.Cryptography.csproj" />
    <ProjectReference Include="../Neo.Protocol/Neo.Protocol.csproj" />
    <ProjectReference Include="../Neo.Protocol.Payloads/Neo.Protocol.Payloads.csproj" />
  </ItemGroup>

</Project>
