<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.9.0" />
    <PackageReference Include="MSTest.TestFramework" Version="3.9.0" />
    <PackageReference Include="BenchmarkDotNet" Version="0.15.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Neo/Neo.csproj" />
    <ProjectReference Include="../../src/Neo.IO/Neo.IO.csproj" />
    <ProjectReference Include="../../src/Neo.Cryptography/Neo.Cryptography.csproj" />
  </ItemGroup>

</Project>
