<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageTags>NEO;Blockchain;Consensus;dBFT</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Neo.Core/Neo.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Neo" />
    <InternalsVisibleTo Include="Neo.Orleans" />
    <InternalsVisibleTo Include="Neo.UnitTests" />
  </ItemGroup>

</Project>
