<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);NU1510;NU1603;NU1902</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.11.0-beta.1" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.11.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\Neo\\Neo.csproj" />
    <ProjectReference Include="..\\Neo.Extensions\\Neo.Extensions.csproj" />
    <ProjectReference Include="..\\Neo.RPC\\Neo.RPC.csproj" />
    <ProjectReference Include="..\\Neo.IO\\Neo.IO.csproj" />
    <ProjectReference Include="..\\Neo.Plugins\\Neo.Plugins.csproj" />
    <ProjectReference Include="..\\Neo.Protocol\\Neo.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

</Project>

