<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <PackageTags>NEO;Blockchain;Storage;Persistence</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Neo.Extensions\Neo.Extensions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Neo" />
    <InternalsVisibleTo Include="Neo.UnitTests" />
  </ItemGroup>

</Project>
