<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <PackageTags>NEO;Blockchain;Observability;Metrics;Tracing</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Neo" />
    <InternalsVisibleTo Include="Neo.UnitTests" />
  </ItemGroup>

</Project>
