<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <PackageTags>NEO;Blockchain;Cryptography;ECC;Hash</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Neo.Core/Neo.Core.csproj" />
    <ProjectReference Include="../Neo.Extensions/Neo.Extensions.csproj" />
    <ProjectReference Include="../Neo.IO/Neo.IO.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Neo" />
    <InternalsVisibleTo Include="Neo.UnitTests" />
  </ItemGroup>

</Project>
